### PR TITLE
Add option to skinsettings: Show logos for scrambled channels

### PR DESCRIPTION
**Pull request by Donderstraal**
My backend (DVBViewer) allows for disscrambling channels through a hardware cam solution, but it still sends a flag along the channel need a subscription. As a consequence the logos for these channels are not displayed. I made an option in skin settings to solve this. Made a whole submenu as I got a few more ideas that would fit right at place there (IE more or less TV guide rows etc).

Before:
Before

After:
After

Setting:
Settings

Hope you agree this is a useful addition to the settings =)

### CODE REVIEW

**Comment by Ch1llb0** [comment]
Will have a closer look the next days. A few thoughts already:

- Adding an extra submenu in the settings for one single setting wouldn't be something I'd like to add though. We've tried keeping the skin settings as clean and simple as possible. I'm not sure we'd need additional settings just for TV/PVR related things.
-> Maybe adding this permanently without a toggle would be better. Or is there a downside to this?
- The lock icon would need a closer look. Is it taken from our skin or is it a new design? Not sure on my small screen - on the road atm. The icon would need to match the skin's icons' design.

**Comment by Donderstraal** [comment]
I agree on keeping it clean and simple, but I'm in a bit of a bind. There's a few things I've got in mind (small improvements) and not sure where to store them. Do as you like as this was a kind of exercise for me, the first time editing a skin.

For me making it a permanent fix would work, not even sure why it was decided to make it this way.

The Lock icon is something that's already in the skin and the default behaviour for scrambled channels.  Again not sure why anyone decided this was a good idea but I can take a best guess here; In Germany/The Netherlands here we have both public channels which are FTA (open) and scrambled channels on for example DVB-T2. I think someone wanted to show there are indeed more channels, just not available for viewing.

Again take your best pick for this, to me it's annoying having 150 channels over DVB-C and only be able to show 20 logos. Took me quite some effort to find where the cause was.

**Comment by Donderstraal** [comment]
As for my other ideas;

- Making the channel logo for the selected channel on the bottom a tad bigger
- Adding the $INFO[ListItem.Genre] info under between the program title and time slot
- And enabling genre colours as many skins have as an option, that's why I looked into a PVR menu
- Some alignment errors/OCD
- Instead of square logo support rectangular logo support; all my logo's are 800x450px (for this there doesn't seem to be a standard though, but I like this 16:9 size a whole lot better)

So nothing too intrusive I think...

**Comment by Donderstraal** [comment]
Proposal

Maybe you like it in this way better... it's an OSD setting overal

**Comment by samnazarko** [comment]
Is this option enabled by default? It probably should be.

**Comment by Donderstraal** [comment]
Variables.xml;

	<variable name="PVRChannelIcon">
		<value condition="ListItem.IsEncrypted">pvr/encrypted.png</value>
		<value>$INFO[ListItem.Thumb]</value>
	</variable>
	
	<variable name="PVRChannelIconDialogOSD">
		<value condition="Container(11).ListItem.IsEncrypted">pvr/encrypted.png</value>
		<value>$INFO[Container(11).ListItem.Thumb]</value>
	</variable>

This is by default, resulting in a lock even if one can descramble the channel

**Comment by Ch1llb0** [comment]
Your addition, @Donderstraal, should indeed take effect by default, I agree with @samnazarko. So, "Show scrambled channel logos" should be "Show lock icon for encrypted PVR channels". Please change it that way and therefore change the condition in Variables.xml to `Skin.HasSetting(PVRShowLock) + ListItem.IsEncrypted`

Also, please have a look at commenting your different commits as per I'm doing it in general (see here for an example: [Improve skinshortcuts dialog](https://github.com/osmc/skin.osmc/commit/9b373561a8edf20d516fce01fb81c3f2847bc546)).

---

The OSD section is only meant for settings related to video and audio player OSD settings - OSD is used in that way in the Kodi terminology. I've quickly reworked the advanced section of our settings to have a bit more structure (and I'll push this before merging this PR):

screenshot001

I'd prefer the setting to go here:

screenshot000

In the code it would be button id 612 here:

Unbenannt

**Comment by Donderstraal** [comment]
Sure, no problem @ all of the above. For me it's a learning curve as I've never done such a thing before and this was great fun trying. I've looked at some of the other things I had in mind (resembling Eminence 2 a bit closer for the EPG window) but the learning curve is quite steep. Especially for genre colour coding which adds a lot I think. Don't want to change too much though. But in general PVR can use a bit more love.

A small inspiration;
Eminence 2
Colour coding for genres / listing the tv channel groups / listing the tv programme genre / also like the weather icon and time in the corner a bit better (don't think the channel logo adds a lot) but I leave that one up to you.

As soon as your commit is pushed will edit SkinSettings.xml  for the final position

**Comment by Ch1llb0** [comment]
Will push soon then! 👍 

The genre colors are somewhat nice, but problematic with our skin. The main design approach of our skin is minimalistic and results in colours only being used by the background and by any type of fan art (which also include channel logos). But adding more colors to the EPG grid view would be distracting and hard to implement as the background will always have a color - and we offer the choice to alter those colors.
Adding things like weather to normal screens is also not an option the way I see it atm... There's no real space left to add it and we wouldn't want too much information on normal screen. We've got the weather section and the weather widget on the home screen for that.

Things like the channel group are available through the wide menu on the left with our skin:

screenshot000

But we could have a look where it might be able to show this in the normal window as well. And the genre - not as a color - probably be added as extra information somewhere as well. We don't offer that atm at all.
I'm not even sure my backend provides any PVR genres atm. Where does that information come from on your setup?

**Comment by Donderstraal** [comment]
> Adding things like weather to normal screens is also not an option the way I see it atm... There's no real space left to add it and we wouldn't want too much information on normal screen. We've got the weather section and the weather widget on the home screen for that.
> 
> Things like the channel group are available through the wide menu on the left with our skin:
> 
> But we could have a look where it might be able to show this in the normal window as well. And the genre - not as a color - probably be added as extra information somewhere as well. We don't offer that atm at all.
>
> I'm not even sure my backend provides any PVR genres atm. Where does that information come from on your setup?

1. I agree on the weather, it's not easy. But now that corner is not consistent with the rest of the minimalistic skin. On the home menu it displays just the time, playing PVR it looks like this, etc... But I won't do anything that that touches the skin in a wide area so don't worry about me doing that. Just mentioning it doesn't fit in and how it could look.

2. Im not using that sub menu, my channel up and down button are mapped to go through the channel groups for my 150+ channels. If I'm not mistaken I got 9 channel groups and this allows for fast looking what's on what channel. But it doesn't bother me too much, the sub menu is there for the people who are on a minimalistic remote. Might do this one myself for me alone as soon as I figure out where this part is.

3. I think genre colour coding would work really well, and I got it in my mind how it would look with this skin and (at least in my mind) it totally works out.  Like the same colours as Eminence but translucent as it is now. As I've seen too it's not easy not straightforward to add. Atm I'm not capable enough to look into this yet I'm afraid, but it's my #1 wish for sure.

4. Skin wise I'm looking into this, as soon as I figure out how I can copy it from Eminence. Backend wise this comes from DVB-C or T2 in my case and is provided as a service. 10 days worth of it. Actually in Europe it's quite common to have this along with your subscription, in the US however you need to pay for it severally I've found out. Adding it through .XML is also possible in TVheadend/DVBViewer/MediaPortal as I've experimented a lot with those. I've settled on DVBViewer as it runs on windows and it does all I need.

**Comment by Ch1llb0** [comment]
1. It is consistent... I have to correct you there. The consistency works like this: If there's no playback, we show the clock (and date, if you enable it). If there's video or audio playback, the place of the clock is taken over by the 'now playing' information. That's already a space compromise, but I don't see a way to do this with a different permanent item like weather information.

2. You'd like a toggle right in the PVR windows to toggle through the channel groups or just information on which group is currently selected?

3. It would be ok, if we added it for just one background color as we could adjust the genre colors to work together with the background color perfectly. But as all colors of the skin can be adjusted with color sets or even completely manually, there would be plenty of scenarios where a genre color would simply not be visible as it would match the background color by accident. We can't have that. The second issue, as I've said, that we don't use any colors other than background, overlay and fanart colors. This would make the PVR EPG view quite colorful and that's not really what the skin's approach currently is.

4. Just had a second look and my backend seems to be providing genres as well. In our skin they're already visible when opening the info screen for a TV program. 👍

**Comment by Ch1llb0** [comment]
Changes needed are pushed and merged now: https://github.com/osmc/skin.osmc/pull/120

Please to rebase/merge them to your fork and update this PR 👍

**Comment by Donderstraal** [comment]
Alright, did I do it right this time? Took some time to figure it all out.
I think for a few commits I didn't quite get the changelog right, it seems to work on my end though.

**Comment by samnazarko** [comment]
It doesn't look like this PR is in a mergeable state.
Can you tidy up some of the commit information and possibly drop: Delete Coordinates_SkinSettings (Autosaved).xml

**Comment by Donderstraal** [comment]
I'm giving up... it's too complicated for me.
On my end the file is deleted and everything looks and works just fine.
Sorry, the learning curve of GitHub is too steep and if I do something wrong I don't seem to have the tools to solve it.

**Comment by Ch1llb0** [comment]
It takes same time to get used to Git and how to handle it... Believe me, I struggled a lot when I started as well. @samnazarko will remember.

What about we close this PR and I quickly implement our idea for the next update? If it's OK with you, it wouldn't be a problem for me to implement it.

**Comment by samnazarko** [comment]
I’m also happy to help and put you on the right path. It depends how much work you’d like to do on the skin.

**Comment by Donderstraal** [comment]
Well either way is fine with me really. I don’t plan on doing too much and some of things I’d like to do are too hard for me. Struggle a lot to find where certain sections of code are.

**Comment by Ch1llb0** [comment]
I'll quickly implement this later today and close the PR. That way your idea will make it into the next update.

Please feel free to post your other ideas on our forum: https://discourse.osmc.tv/c/feature-requests Maybe other users also have ideas or thoughts they'd like to add. If you need help with the code, feel free to PM me over on Discourse - I might be able to help out a bit. Ideas and input from uses are always welcome!

**Comment by Ch1llb0** [comment]
See this commit: https://github.com/osmc/skin.osmc/commit/d6a288d759b38a6d85074f41c3cdb04cacc06a6c

Will close this now. Maybe see you on the forum! 👍

**Pull request closed without merging**
