### PR TITLE
Hide seekbar on tempo

### PR DESCRIPTION
**Pull request by svenjochems**

### CODE REVIEW

**Comment by samnazarko** [comment]
@Ignoble61 Up to you if you think this should be merged [1] 

[1] https://discourse.osmc.tv/t/playback-speed-issues/22527

**Comment by Ignoble61** [comment]
Current behaviour on tempo is consistent with other trick-plays (skip, ffwd, etc). Can you explain why changing this behaviour is preferred?

**Comment by svenjochems** [comment]
​I like to watch videos at an increased tempo (x1.1 or x1.2), I find it
annoying that the seekbar stays visible in this situation because the
subtitles aren't visible anymore. I do get why it stays visible on skip,
ffwd, etc, nobody really whatches the video during these actions.​

**Comment by Ignoble61** [comment]
Thanks. I appreciate the requirement to handle tempo play differently from other trick-plays, particularly when subtitles are displayed.

My primary concern is that when any trick play is being used, some controls act differently - for example, PlayPause will resume playing at normal speed rather than pausing as it would during normal playback. Therefore we need to ensure that, when trick play is in effect, this is reflected onscreen.

As such I'm happy to merge these changes, but be aware that I'll be reviewing them in the next few days to ensure that - though the full seek bar won't be displayed - there is still an indication that trick-play is active. If you have any further suggestions on this let me know.

**Comment by svenjochems** [comment]
Thanks for merging

I understand your concerns, maybe it's a good idea to only show the little
box with the playback speed but hide the rest of the seekbar. This way the
user is indicated that a trick-play is activate while keeping the
disturbance minimal.

Anyway, thanks for considering this feature

**Pull request merged**
