### PR TITLE
Update Includes.xml

### PR DESCRIPTION
**Pull request by JoEnzo8051**
minor addition: added date above time.

### CODE REVIEW

**Comment by Wuschel-Wuschel** [comment]
Finding it very problematic in terms of the overall layout (clock on the right and window headings on the left are just one-line each, which should stay that way). Would probably look cluttered IMHO. Haven't seen a request for this before, so not sure whether it's a good idea to add this for everyone.

**Comment by graham8** [comment]
Not supported.

**Comment by JoEnzo8051** [comment]
I did oversaw the alignement with the other skin elements, which is indeed not good in terms of consistency. I however do not understand what you mean by 'window headings on the left'. Is there an invisible element on the left? Or do you mean the OSMC logo?

Personally I do not always remember which day it is. Since our TV is almost constantly on when being home (e.g. music playing), it is very convenient to have the date on the Home screen. Since - in my humble opinion - it does not clutter things, I tought that our fellow osmc-skin users would a) not need and not mind this minor feature, or b) find it convenient as I do.

I would like to ask you kindly to look at the result of this proposed addition on your actual kodi screen. If you then still believe it clutters things than I will respect that. If it does not, maybe it can be implemented in a way that does not alter the consistency of alignments etc?

As I am quite new to consumer application programming (I used to program PLC and DCS systems for industrial clients), I realise that there are other elements - that I am not yet aware of - to be considered as well. I am always eager to learn ;)

**Comment by Wuschel-Wuschel** [comment]
I've taken a closer look at what you're proposing. Just as a short explanation: the window headings appear as soon as you open a window like music e.g. They're shown instead of the OSMC logo then.

Two problems with your proposal:
1.) Moving the clock down collides with wall view in the music and film/TV show episode sections of the library. Those views can't be changed (they're already using as much or less space as possible).
2.) If we'd move the date and clock up a bit, it move into the frame left empty around all elements at all time (which is there as part of the minimalistic look).

Only way would be to add the date in the same line as the clock (probably in front of the clock), but the team has to decide on this. I'll get back to you regarding this.

**Comment by Wuschel-Wuschel** [comment]
Keep your eyes peeled for the next update ;)

**Pull request closed without merging**
