### PR TITLE
Add spanish translation

### PR DESCRIPTION
**Pull request by roliverosc**

### CODE REVIEW

**Comment by Ch1llb0** [comment]
Our skin will be translated via the Kodi Transifex system. It's already been added to the translation process. Therefore, all translation will be pushed back to our repo from Transifex and translations of single languages cannot be accepted here.

**Comment by roliverosc** [comment]
What is the url?

**Comment by Ch1llb0** [comment]
The Transifex system is not open to contribution, but you may well apply to become a translator here: https://www.transifex.com/teamxbmc/kodi-skins/

**Comment by roliverosc** [comment]
Ok but many chains missing on transifex.

**Comment by Ch1llb0** [comment]
The translation over there is going slow, yes. But we can't mix things from here and there. We have to be patient or you may register with Transifex and help out.

**Pull request closed without merging**
